### ISSUE TITLE
Provozovat jako Docker Runner appku

### ISSUE THREAD

**Issue by Halama** [keboola/ssh-keygen-api#2]
Teď už podporujeme sync akce tak není tohle potřeba provozovat separátně. Bude lepší když se to bude spravovat stejně jako ostatní komponenty. Zároveň kvůli tomu nebudeme muset provozovat separátní ELB.

**Comment by ErikZigo** [comment]
Uz skoro rok provozujeme https://github.com/keboola/ssh-keygen `keboola.ssh-keygen-v2`

Tohle asi zustalo omylem otevreny
